USE DATABASE CDC_SQL_DB;

-- Logging tabellen legen SQL versie
TRUNCATE TABLE LOGGING.RUN_LOG;
TRUNCATE TABLE LOGGING.RUN_ENTITY_LOG;
TRUNCATE TABLE LOGGING.RUN_ERROR_LOG;

-- -- Config legen
TRUNCATE TABLE CDC.CDC_CONFIG;

-- Staging tabellen legen SQL versie
TRUNCATE TABLE STAGING.S_EMPLOYEE;
TRUNCATE TABLE STAGING.S_CUSTOMER;
TRUNCATE TABLE STAGING.S_ORDER;

-- Target tabellen legen SQL versie
TRUNCATE TABLE TARGET.T_EMPLOYEE;
TRUNCATE TABLE TARGET.T_CUSTOMER;
TRUNCATE TABLE TARGET.T_ORDER;


USE DATABASE CDC_PYTHON_DB;

-- Logging tabellen legen PYTHON versie
TRUNCATE TABLE LOGGING.RUN_LOG;
TRUNCATE TABLE LOGGING.RUN_ENTITY_LOG;
TRUNCATE TABLE LOGGING.RUN_ERROR_LOG;

-- -- Config legen
TRUNCATE TABLE CDC.CDC_CONFIG;

-- Staging tabellen legen PYTHON versie
TRUNCATE TABLE STAGING.S_EMPLOYEE;
TRUNCATE TABLE STAGING.S_CUSTOMER;
TRUNCATE TABLE STAGING.S_ORDER;

-- Target tabellen legen PYTHON versie
TRUNCATE TABLE TARGET.T_EMPLOYEE;
TRUNCATE TABLE TARGET.T_CUSTOMER;
TRUNCATE TABLE TARGET.T_ORDER;

