
CALL merge_non_duplicates();
TRUNCATE TABLE STAGING.EmployeeSalary;


SELECT COUNT(*) AS TOTAL_ROWS FROM STAGING.S_EMPLOYEE;

SELECT COUNT(*) AS TOTAL_ROWS FROM TARGET.T_EMPLOYEE;

TRUNCATE TABLE LOGGING.RUN_LOG;
TRUNCATE TABLE STAGING.S_EMPLOYEE;

TRUNCATE TABLE TARGET.T_EMPLOYEE;

TRUNCATE TABLE CDC.CDC_CONFIG;

INSERT INTO CDC.CDC_CONFIG (
    CONFIG_ID, ENTITY_NAME, SOURCE_TABLE, TARGET_TABLE, PRIMARY_KEY_COLUMN,
    DELETE_STRATEGY, ERROR_STRATEGY, UPDATE_STRATEGY, IS_ACTIVE
) VALUES (
    1, 'Employee', 'STAGING.S_Employee', 'TARGET.T_Employee', 'EMPLOYEE_ID',
    'SOFT', 'CONTINUE', 'HISTORY', TRUE
);

INSERT INTO CDC.CDC_CONFIG (
    CONFIG_ID, ENTITY_NAME, SOURCE_TABLE, TARGET_TABLE, PRIMARY_KEY_COLUMN,
    DELETE_STRATEGY, ERROR_STRATEGY, UPDATE_STRATEGY, IS_ACTIVE
) VALUES (
    2, 'Customer', 'STAGING.S_Customer', 'TARGET.T_Customer', 'CUSTOMER_ID',
    'SOFT', 'CONTINUE', 'HISTORY', TRUE
);

INSERT INTO CDC.CDC_CONFIG (
    CONFIG_ID, ENTITY_NAME, SOURCE_TABLE, TARGET_TABLE, PRIMARY_KEY_COLUMN,
    DELETE_STRATEGY, ERROR_STRATEGY, UPDATE_STRATEGY, IS_ACTIVE
) VALUES (
    3, 'Order', 'STAGING.S_Order', 'TARGET.T_Order', 'ORDER_ID',
    'SOFT', 'CONTINUE', 'HISTORY', TRUE
);

CALL CDC.CDC_RUN();

SELECT * FROM LOGGING.RUN_ERROR_LOG WHERE ERROR_CODE = '';

SELECT * FROM STAGING.S_EMPLOYEE;

SELECT * FROM TARGET.T_EMPLOYEE;

DELETE FROM CDC_SQL_DB.LOGGING.RUN_LOG WHERE RUN_ID = 18;
DELETE FROM CDC_PYTHON_DB.LOGGING.RUN_LOG WHERE RUN_ID = 18;


SELECT
    EMPLOYEE_ID,
    SALARY,
    MANAGER,
    DEPARTMENT,
    METADATA$ACTION,
    METADATA$ISUPDATE,
    METADATA$ROW_ID
FROM CDC_STREAMS_DB.STAGING.STAGING_SOURCE_TABLE_STREAM;

UPDATE CDC_STREAMS_DB.STAGING.S_EMPLOYEE SET SALARY = 5022 WHERE EMPLOYEE_ID = 'R000007';

DELETE FROM CDC_STREAMS_DB.STAGING.S_EMPLOYEE WHERE EMPLOYEE_ID = 'R000034';

create temp table
clear_the_stream as
(select * from cdc_streams_db.staging.staging_source_table_stream);
select count(*) from cdc_streams_db.staging.staging_source_table_stream; --now returns 0 since the offset has been reset.

USE DATABASE CDC_PYTHON_DB;
UPDATE STAGING.S_EMPLOYEE
SET SALARY = SALARY + 400
WHERE EMPLOYEE_ID IN ('R000001', 'R000002', 'R000003', 'R000004', 'R000005');

DELETE FROM STAGING.S_EMPLOYEE
WHERE EMPLOYEE_ID IN ('R000007', 'R000008');

DESCRIBE TABLE CDC_SQL_DB.STAGING.S_EMPLOYEE;

SELECT * FROM CDC_SQL_DB.LOGGING.RUN_LOG;




employee_id = result[0]
salary = result[1]

employee_id = result["employee_id"]
salary = result["salary"];


USE DATABASE CDC_SQL_DB;
USE SCHEMA TARGET;

CREATE OR REPLACE TABLE T_TEST_WITH_CDC(
  ROW_HASH STRING(64),
  START_TS TIMESTAMP_NTZ,
  END_TS TIMESTAMP_NTZ,
  IS_ACTIVE BOOLEAN DEFAULT TRUE,
  CDC_OPERATION STRING, -- 'I', 'U', 'D'
  ID STRING,
  NAAM STRING(100),
  WOONPLAATS STRING(100),
  PRIMARY KEY (ID, START_TS)
);

CREATE OR REPLACE TABLE T_TEST_WITHOUT_CDC(
  ID STRING,
  NAAM STRING(100),
  WOONPLAATS STRING(100),
  PRIMARY KEY (ID)
);

USE SCHEMA STAGING;
CREATE OR REPLACE TABLE S_TEST_WITH_CDC(
  ID STRING,
  NAAM STRING(100),
  WOONPLAATS STRING(100),
  PRIMARY KEY (ID)
);

