
CALL merge_non_duplicates();
TRUNCATE TABLE STAGING.EmployeeSalary;


SELECT COUNT(*) AS TOTAL_ROWS FROM STAGING.S_EMPLOYEE;

SELECT COUNT(*) AS TOTAL_ROWS FROM TARGET.T_EMPLOYEE;

TRUNCATE TABLE LOGGING.RUN_LOG;
TRUNCATE TABLE STAGING.S_EMPLOYEE;

TRUNCATE TABLE TARGET.T_EMPLOYEE;

TRUNCATE TABLE CDC.CDC_CONFIG;

INSERT INTO CDC.CDC_CONFIG (
    CONFIG_ID, ENTITY_NAME, SOURCE_TABLE, TARGET_TABLE, PRIMARY_KEY_COLUMN,
    DELETE_STRATEGY, ERROR_STRATEGY, UPDATE_STRATEGY, IS_ACTIVE
) VALUES (
    1, 'Employee', 'STAGING.S_Employee', 'TARGET.T_Employee', 'EMPLOYEE_ID',
    'SOFT', 'CONTINUE', 'HISTORY', TRUE
);

INSERT INTO CDC.CDC_CONFIG (
    CONFIG_ID, ENTITY_NAME, SOURCE_TABLE, TARGET_TABLE, PRIMARY_KEY_COLUMN,
    DELETE_STRATEGY, ERROR_STRATEGY, UPDATE_STRATEGY, IS_ACTIVE
) VALUES (
    2, 'Customer', 'STAGING.S_Customer', 'TARGET.T_Customer', 'CUSTOMER_ID',
    'SOFT', 'CONTINUE', 'HISTORY', TRUE
);

INSERT INTO CDC.CDC_CONFIG (
    CONFIG_ID, ENTITY_NAME, SOURCE_TABLE, TARGET_TABLE, PRIMARY_KEY_COLUMN,
    DELETE_STRATEGY, ERROR_STRATEGY, UPDATE_STRATEGY, IS_ACTIVE
) VALUES (
    3, 'Order', 'STAGING.S_Order', 'TARGET.T_Order', 'ORDER_ID',
    'SOFT', 'CONTINUE', 'HISTORY', TRUE
);

CALL CDC.CDC_RUN();

SELECT * FROM LOGGING.RUN_ERROR_LOG WHERE ERROR_CODE = '';

SELECT * FROM STAGING.S_EMPLOYEE;
