-- ------------------------------------------------
-- Met CDC component
-- ------------------------------------------------
USE DATABASE CDC_SQL_DB;

USE SCHEMA TARGET;

-- Geleegde startsituatie
TRUNCATE TABLE TARGET.T_TEST_WITH_CDC;
TRUNCATE TABLE TARGET.T_TEST_WITHOUT_CDC;
TRUNCATE TABLE STAGING.S_TEST_WITH_CDC;
TRUNCATE TABLE LOGGING.RUN_LOG;
TRUNCATE TABLE LOGGING.RUN_ENTITY_LOG;
TRUNCATE TABLE LOGGING.RUN_ERROR_LOG;
TRUNCATE TABLE CDC.CDC_CONFIG;

-- CDC configuratie invullen

INSERT INTO CDC.CDC_CONFIG (
		ENTITY_NAME,
		SOURCE_TABLE,
		TARGET_TABLE,
		PRIMARY_KEY_COLUMN,
		DELETE_STRATEGY,
		ERROR_STRATEGY,
		UPDATE_STRATEGY,
		IS_ACTIVE
)
VALUES (
		'Test_with_CDC',
		'STAGING.S_TEST_WITH_CDC',
		'TARGET.T_TEST_WITH_CDC',
		'ID',
		'SOFT',
		'CONTINUE',
		'HISTORY',
		TRUE
);

-- Run 1
USE SCHEMA STAGING;
TRUNCATE TABLE S_TEST_WITH_CDC;
INSERT INTO S_TEST_WITH_CDC (ID, NAAM, WOONPLAATS)
VALUES
		('1', 'John Doe', 'Arnhem'),
		('2', 'Jane Doe', 'Arnhem');

CALL CDC.CDC_RUN();

-- Run 2
TRUNCATE TABLE S_TEST_WITH_CDC;
INSERT INTO S_TEST_WITH_CDC (ID, NAAM, WOONPLAATS)
VALUES
		('1', 'John Doe', 'Arnhem'),
		('2', 'Jane de Wit', 'Maastricht'),
		('', 'Emma Ptykee', 'Rotterdam');

CALL CDC.CDC_RUN();

-- Resultaten
SELECT *
FROM TARGET.T_TEST_WITH_CDC
ORDER BY ID, START_TS;